package com.bank.model;
// Generated Oct 28, 2018 3:19:08 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BankInfo generated by hbm2java
 */
@Entity
@Table(name="bank_info"
    ,catalog="bank"
    , uniqueConstraints = @UniqueConstraint(columnNames="bank_id") 
)
public class BankInfo  implements java.io.Serializable {


     private Integer id;
     private String bankId;
     private String bankName;
     private String bankAddress;
     private String bankContactno;
     private String bankEmail;
     private String bankLogo;
     private Set<User> users = new HashSet<User>(0);

    public BankInfo() {
    }

    public BankInfo(String bankId, String bankName, String bankAddress, String bankContactno, String bankEmail, String bankLogo, Set<User> users) {
       this.bankId = bankId;
       this.bankName = bankName;
       this.bankAddress = bankAddress;
       this.bankContactno = bankContactno;
       this.bankEmail = bankEmail;
       this.bankLogo = bankLogo;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="bank_id", unique=true, length=25)
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }

    
    @Column(name="bank_name", length=200)
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    
    @Column(name="bank_address", length=400)
    public String getBankAddress() {
        return this.bankAddress;
    }
    
    public void setBankAddress(String bankAddress) {
        this.bankAddress = bankAddress;
    }

    
    @Column(name="bank_contactno", length=30)
    public String getBankContactno() {
        return this.bankContactno;
    }
    
    public void setBankContactno(String bankContactno) {
        this.bankContactno = bankContactno;
    }

    
    @Column(name="bank_email", length=100)
    public String getBankEmail() {
        return this.bankEmail;
    }
    
    public void setBankEmail(String bankEmail) {
        this.bankEmail = bankEmail;
    }

    
    @Column(name="bank_logo", length=100)
    public String getBankLogo() {
        return this.bankLogo;
    }
    
    public void setBankLogo(String bankLogo) {
        this.bankLogo = bankLogo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bankInfo")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


